version: '2.4'
services:
  langchain_app:
    image: langchain_app
    build:
      context: .
      dockerfile: dockerfile_ros
    volumes:
      - ../ReAct:/root/ReAct
    ports:
      - "11434:11434"
    tty: true
    network_mode: "host"
    environment: 
          - ROS_MASTER_URI=${ROS_MASTER_URI:-http://127.0.0.1:11311}
          - ROS_IP=${ROS_IP:-127.0.0.1}